model:
  name: "yolo11n.pt"
  best: "/home-mscluster/nmaja/Yolo-Based-Object-Detection-on-Car-Crash-Data/runs/train/custom_yolo_model18/weights/best.pt"

dataset:
  yaml: "dataset.yaml"

#Training Parameters
train:
  epochs: 50
  imgsz: 640
  batch: 16
  project: "runs/train"
  experiment_name: "custom_yolo_model"
  save_model: true

#Validation Parameters
val:
  epochs: 50
  split: "val"
  imgsz: 640
  batch: 16
  conf: 0.25
  iou: 0.6
  save_model: true

compute:
  training_strategy: "multi"   # single | multi
  validation_strategy: "simple"

paths:
  local_base: "C:/Users/neokg/Coding_Projects/yolo-detector/car_crash_dataset/CCD_images"
  local_model: "C:/Users/neokg/Coding_Projects/yolo-detector/downloaded_model/weights/best.pt"
  cluster_base: "/datasets/nmaja/CrashBest"
  cluster_model: "/home-mscluster/nmaja/Yolo-Based-Object-Detection-on-Car-Crash-Data/runs/train/custom_yolo_model18/weights/best.pt"