model:
  name: "yolo11n.pt"
  best: "/cluster_project_location/runs/train/custom_yolo_model18/weights/best.pt"

dataset:
  yaml: "dataset.yaml"

#Training Parameters
train:
  epochs: 50
  imgsz: 640
  batch: 16
  project: "runs/train"
  experiment_name: "custom_yolo_model"
  save_model: true

#Validation Parameters
val:
  epochs: 50
  split: "val"
  imgsz: 640
  batch: 16
  conf: 0.25
  iou: 0.6
  save_model: true

compute:
  training_strategy: "multi"   # single | multi
  validation_strategy: "simple"

paths:
  local_base: "C:/Users/project_location/CCD_images"
  local_model: "C:/Users/project_location/downloaded_model/weights/best.pt"
  local_normal_images: "C:/Users/project_location/CCD_images/normal_images"
  cluster_base: "/cluster_db_location/CrashBest"
  cluster_model: "/cluster_project_location/runs/train/custom_yolo_model18/weights/best.pt"
  cluster_normal_images: "/cluster_db_location/CrashBest/normal_files"