model:
  name: "yolo11n.pt"

dataset:
  yaml: "dataset.yaml"

#Training Parameters
train:
  epochs: 50
  imgsz: 640
  batch: 16
  project: "runs/train"
  experiment_name: "custom_yolo_model"
  save_model: true

#Validation Parameters
val:
  epochs: 50
  split: "val"
  imgsz: 640
  batch: 16
  conf: 0.25
  iou: 0.6
  save_model: true

compute:
  training_strategy: "multi"   # single | multi
  validation_strategy: "simple"
